# Generated by Selenium IDE
import time
import uuid
from selenium.webdriver.common.by import By

from core.environment.host import get_host_for_selenium_testing
from core.selenium.common import close_driver, initialize_driver


class TestSessions():
  def setup_method(self, method):
    self.driver = initialize_driver()
    self.vars = {}
  
  def teardown_method(self, method):
    close_driver(self.driver)
  
  def test_sessions(self):
    
    # Login flow
    self.driver.get(get_host_for_selenium_testing())
    self.driver.set_window_size(1070, 1063)
    self.driver.find_element(By.CSS_SELECTOR, ".navbar").click()
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "email").send_keys("user3@example.com")
    self.driver.find_element(By.ID, "submit").click()
    time.sleep(1)  # Wait for login
    
    # Profile and close sessions
    self.driver.find_element(By.LINK_TEXT, "Smith, Alice").click()
    self.driver.find_element(By.LINK_TEXT, "My profile").click()
    time.sleep(2)  # Wait for sessions to load
    self.driver.find_element(By.ID, "close-all-sessions").click()
    time.sleep(1)  # Wait for AJAX
    
    # Logout
    self.driver.find_element(By.LINK_TEXT, "Smith, Alice").click()
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
    time.sleep(1)
    
    # Signup flow with unique email
    unique_email = f"user_{uuid.uuid4().hex[:8]}@example.com"
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link:nth-child(2)").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("Fran")
    self.driver.find_element(By.ID, "surname").send_keys("Sabido")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys(unique_email)
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, ".content").click()
    self.driver.find_element(By.ID, "submit").click()
    time.sleep(2)  # Wait for signup
    
    # Profile and close sessions again
    self.driver.find_element(By.CSS_SELECTOR, ".text-dark").click()
    self.driver.find_element(By.LINK_TEXT, "My profile").click()
    time.sleep(2)  # Wait for sessions to load
    self.driver.find_element(By.ID, "close-all-sessions").click()
    time.sleep(1)  # Wait for AJAX
    
    # Final logout
    self.driver.find_element(By.CSS_SELECTOR, ".text-dark").click()
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
  