"""Add is_active to user_sessions

Revision ID: 006
Revises: 005
Create Date: 2025-12-12 16:21:20.721940

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy import inspect
from sqlalchemy.engine import reflection


# revision identifiers, used by Alembic.
revision = '006'
down_revision = '005'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = reflection.Inspector.from_engine(conn)
    columns = [col['name'] for col in inspector.get_columns('user_sessions')]
    if 'is_active' not in columns:
        op.add_column('user_sessions', sa.Column('is_active', sa.Boolean()))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
