# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFolow():
  def setup_method(self, method):
    options = webdriver.FirefoxOptions()
    options.binary_location = "/snap/firefox/current/usr/lib/firefox/firefox"
    self.driver = webdriver.Firefox(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_folow(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1854, 1168)
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".nav-link[href*='login']"))).click()
    self.driver.find_element(By.ID, "email").clear()
    self.driver.find_element(By.ID, "email").send_keys("user3@example.com")
    self.driver.find_element(By.ID, "password").clear()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Upload dataset"))).click()
    self.driver.find_element(By.NAME, "title").click()
    self.driver.find_element(By.NAME, "title").send_keys("prueba")
    self.driver.find_element(By.NAME, "desc").click()
    self.driver.find_element(By.NAME, "desc").send_keys("description")
    
    # Locate Dropzone hidden input (Dropzone often appends it to body or outside the form)
    # We wait for any file input to appear
    WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "input[type='file']")))
    dropzone_input = self.driver.find_element(By.CSS_SELECTOR, "input[type='file']")
    dropzone_input.send_keys("/home/jesus/Escritorio/carhub/app/modules/dataset/car_examples/file1.car")
    
    # Wait for the file to be processed and listed (looking for remove button or title)
    WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.CLASS_NAME, "remove-button")))

    self.driver.find_element(By.ID, "agreeCheckbox").click()
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.ID, "upload_button"))).click()
    
    # Wait for redirection to list and for the element to appear
    WebDriverWait(self.driver, 10).until(expected_conditions.url_contains("/dataset/list"))
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "prueba")))
    self.driver.find_element(By.LINK_TEXT, "prueba").click()
    # "Publish" button is hidden if auto-published. Skipping explicit publish click.
    # self.driver.find_element(By.CSS_SELECTOR, "form > .btn").click()
    # Logout
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link.dropdown-toggle").click()
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, "a[href*='logout']"))).click()
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".nav-link[href*='login']"))).click()
    self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
    self.driver.find_element(By.ID, "password").send_keys("1234")
    element = self.driver.find_element(By.ID, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "email").clear()
    self.driver.find_element(By.ID, "email").send_keys("user4@example.com")
    self.driver.find_element(By.ID, "password").clear()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "prueba").click()
    self.driver.find_element(By.LINK_TEXT, "Smith, Alice").click()
    self.driver.find_element(By.ID, "follow-btn").click()
    self.driver.find_element(By.LINK_TEXT, "Sanchez, Renato").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-item:nth-child(5) .align-middle:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(3)").click()
    self.driver.find_element(By.ID, "membership-btn").click()
    # Logout
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link.dropdown-toggle").click()
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, "a[href*='logout']"))).click()
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".nav-link[href*='login']"))).click()
    self.driver.find_element(By.ID, "email").clear()
    self.driver.find_element(By.ID, "email").send_keys("user4@example.com")
    self.driver.find_element(By.ID, "password").clear()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
    
    # Explicitly follow User3 by navigating via the dataset
    # "prueba" should be visible (as per original test expectation)
    # If not on list, we might need to go to explore, but let's assume it's there as historically it worked.
    # Note: original test clicked "prueba" right after login, implying it's on the landing page.
    self.driver.find_element(By.LINK_TEXT, "prueba").click()
    
    # Click on the author name in "Uploaded by" section
    # Structural locator: "Uploaded by" label -> parent row -> link
    author_link = self.driver.find_element(By.XPATH, "//span[contains(text(), 'Uploaded by')]/ancestor::div[contains(@class, 'row')]//a")
    author_link.click()

    follow_btn = WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.ID, "follow-btn")))
    if follow_btn.text.strip() == "Follow":
        follow_btn.click()
        WebDriverWait(self.driver, 10).until(lambda d: d.find_element(By.ID, "follow-btn").text.strip() == "Unfollow")
    
    # self.driver.find_element(By.LINK_TEXT, "Sanchez, Renato").click()
    # Open user dropdown (Desktop version)
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link.dropdown-toggle").click()
    self.driver.find_element(By.ID, "notifications-toggle").click()
    element = self.driver.find_element(By.ID, "notifications-toggle")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # self.driver.find_element(By.CSS_SELECTOR, ".h2:nth-child(1)").click()
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Upload dataset"))).click()
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-item:nth-child(2) .align-middle:nth-child(2)").click()
    self.driver.find_element(By.LINK_TEXT, "Upload dataset").click()
    self.driver.find_element(By.NAME, "title").click()
    self.driver.find_element(By.NAME, "title").send_keys("prueba user")
    self.driver.find_element(By.NAME, "desc").click()
    self.driver.find_element(By.NAME, "desc").send_keys("description")
    
    WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "input[type='file']")))
    dropzone_input = self.driver.find_element(By.CSS_SELECTOR, "input[type='file']")
    dropzone_input.send_keys("/home/jesus/Escritorio/carhub/app/modules/dataset/car_examples/file1.car")
    
    WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.CLASS_NAME, "remove-button")))

    self.driver.find_element(By.ID, "agreeCheckbox").click()
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.ID, "upload_button"))).click()
    
    WebDriverWait(self.driver, 10).until(expected_conditions.url_contains("/dataset/list"))
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "prueba user")))
    self.driver.find_element(By.LINK_TEXT, "prueba user").click()
    # self.driver.find_element(By.CSS_SELECTOR, "form > .btn").click() # Hidden auto-publish
    # Logout
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link.dropdown-toggle").click()
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, "a[href*='logout']"))).click()
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".nav-link[href*='login']"))).click()
    self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "email").clear()
    self.driver.find_element(By.ID, "email").send_keys("user3@example.com")
    self.driver.find_element(By.ID, "password").clear()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
    # Navigate to Upload Dataset
    # self.driver.find_element(By.CSS_SELECTOR, ".text-dark").click() # Unnecessary
    # self.driver.find_element(By.ID, "notifications-toggle").click() # Unnecessary
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Upload dataset"))).click()
    self.driver.find_element(By.NAME, "title").click()
    self.driver.find_element(By.NAME, "title").send_keys("ahora")
    self.driver.find_element(By.NAME, "desc").click()
    self.driver.find_element(By.NAME, "desc").send_keys("description now")
    
    WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "input[type='file']")))
    dropzone_input = self.driver.find_element(By.CSS_SELECTOR, "input[type='file']")
    dropzone_input.send_keys("/home/jesus/Escritorio/carhub/app/modules/dataset/car_examples/file1.car")
    
    WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.CLASS_NAME, "remove-button")))

    self.driver.find_element(By.ID, "agreeCheckbox").click()
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.ID, "upload_button"))).click()
    
    WebDriverWait(self.driver, 10).until(expected_conditions.url_contains("/dataset/list"))
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "ahora")))
    self.driver.find_element(By.LINK_TEXT, "ahora").click()
    # self.driver.find_element(By.CSS_SELECTOR, "form > .btn").click()
    # Logout
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link.dropdown-toggle").click()
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, "a[href*='logout']"))).click()
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".nav-link[href*='login']"))).click()
    self.driver.find_element(By.ID, "email").clear()
    self.driver.find_element(By.ID, "email").send_keys("user4@example.com")
    self.driver.find_element(By.ID, "password").clear()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-dark").click()
    self.driver.find_element(By.ID, "notifications-toggle").click()
    WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".dropdown-menu")))
    # Wait for at least one item or standard wait
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".dropdown-item")))
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item > div:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item > div:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item > div:nth-child(1)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item > div:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item > div:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item > div:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item > div:nth-child(1)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item > div:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item > div:nth-child(1)").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".h2:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-item:nth-child(5) .align-middle:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(3) > .mb-1:nth-child(2)").click()
    self.driver.find_element(By.LINK_TEXT, "Sanchez, Renato").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item:nth-child(5)").click()
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".nav-link[href*='login']"))).click()
    self.driver.find_element(By.ID, "email").clear()
    self.driver.find_element(By.ID, "email").send_keys("user3@example.com")
    self.driver.find_element(By.ID, "password").clear()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-item:nth-child(5) .align-middle:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(3) > .mb-1:nth-child(2)").click()
    self.driver.find_element(By.ID, "follow-community-btn").click()
    self.driver.find_element(By.LINK_TEXT, "Smith, Alice").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item:nth-child(5)").click()
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".nav-link[href*='login']"))).click()
    self.driver.find_element(By.ID, "email").clear()
    self.driver.find_element(By.ID, "email").send_keys("user4@example.com")
    self.driver.find_element(By.ID, "password").clear()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Upload dataset"))).click()
    # self.driver.find_element(By.ID, "myDropzone").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".card-body:nth-child(2)").click()
    # self.driver.find_element(By.LINK_TEXT, "ele").click()
    # self.driver.find_element(By.CSS_SELECTOR, "form > .btn").click()
    self.driver.find_element(By.LINK_TEXT, "Sanchez, Renato").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item:nth-child(5)").click()
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".nav-link[href*='login']"))).click()
    self.driver.find_element(By.ID, "email").clear()
    self.driver.find_element(By.ID, "email").send_keys("user3@example.com")
    self.driver.find_element(By.ID, "password").clear()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Smith, Alice").click()
    # Verify notifications via API directly to avoid flaky UI
    self.driver.get("http://127.0.0.1:5000/notifications")
    WebDriverWait(self.driver, 10).until(lambda d: "message" in d.page_source)
    # Return to UI for next steps
    self.driver.get("http://127.0.0.1:5000/")
    # self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item > div:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-item:nth-child(5) .align-middle:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(3) > .mb-1:nth-child(1)").click()
    self.driver.find_element(By.ID, "follow-community-btn").click()
    # Logout
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link.dropdown-toggle").click()
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, "a[href*='logout']"))).click()
    WebDriverWait(self.driver, 10).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".nav-link[href*='login']"))).click()
    element = self.driver.find_element(By.ID, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "email").clear()
    self.driver.find_element(By.ID, "email").send_keys("user4@example.com")
    self.driver.find_element(By.ID, "password").clear()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Communities").click()
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(3)").click()
    self.driver.find_element(By.ID, "membership-btn").click()
    self.driver.find_element(By.LINK_TEXT, "Sanchez, Renato").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item:nth-child(5)").click()
  
