# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from core.selenium.common import initialize_driver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from core.environment.host import get_host_for_selenium_testing
from core.selenium.common import close_driver, initialize_driver

class TestTestSelenium():
  def setup_method(self, method):
    self.driver = initialize_driver()
    self.vars = {}
  
  def teardown_method(self, method):
    close_driver(self.driver)
  
  def test_testSelenium(self):
    self.driver.get(get_host_for_selenium_testing())
    self.driver.set_window_size(758, 1013)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("user3@example.com")
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-toggle").click()
    # Wait until the sidebar item is clickable. Previously this raised
    # ElementNotInteractableException because the element couldn't be
    # scrolled into view or wasn't yet interactable.
    wait = WebDriverWait(self.driver, 10)
    sidebar_item = wait.until(
      EC.element_to_be_clickable((By.CSS_SELECTOR, ".sidebar-item:nth-child(3) .align-middle:nth-child(2)"))
    )
    # Ensure it's in view then click
    try:
      self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", sidebar_item)
    except Exception:
      # ignore if scrolling is not supported for the current driver
      pass
    sidebar_item.click()
    self.driver.find_element(By.ID, "community_filter").click()
    dropdown = self.driver.find_element(By.ID, "community_filter")
    dropdown.find_element(By.XPATH, "//option[. = 'Carreras']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#community_filter > option:nth-child(2)").click()
    self.driver.find_element(By.ID, "community_filter").click()
    dropdown = self.driver.find_element(By.ID, "community_filter")
    dropdown.find_element(By.XPATH, "//option[. = 'De mercado']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#community_filter > option:nth-child(3)").click()
    self.driver.find_element(By.ID, "community_filter").click()
    dropdown = self.driver.find_element(By.ID, "community_filter")
    dropdown.find_element(By.XPATH, "//option[. = 'Eléctricos']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#community_filter > option:nth-child(4)").click()
    self.driver.find_element(By.ID, "community_filter").click()
    dropdown = self.driver.find_element(By.ID, "community_filter")
    dropdown.find_element(By.XPATH, "//option[. = 'Any']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#community_filter > option:nth-child(1)").click()
    self.driver.find_element(By.ID, "query").click()
    self.driver.find_element(By.ID, "query").send_keys("sample dataset 1")
    self.driver.find_element(By.ID, "query").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "query").send_keys("sample dataset 2")
    self.driver.find_element(By.ID, "query").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "query").click()
    self.driver.find_element(By.ID, "query").click()
    element = self.driver.find_element(By.ID, "query")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "query").click()
    self.driver.find_element(By.ID, "query").click()
    self.driver.find_element(By.ID, "query").click()
    self.driver.find_element(By.ID, "query").click()
    element = self.driver.find_element(By.ID, "query")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "query").send_keys("author 2")
    self.driver.find_element(By.ID, "query").send_keys(Keys.ENTER)
  
